services:
  rabbit:
    image: rabbitmq:3-management-alpine
    
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
      
    environment:
      RABBITMQ_DEFAULT_USER: "rq"
      RABBITMQ_DEFAULT_PASS: "rq"
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RABBIT_HOST: 'rabbit'
      RABBIT_PORT: 5672
      RABBIT_USER: 'rq'
      RABBIT_PASSWORD: 'rq'
      QUEUE_NAME: 'line_provider'
      INTERVAL_TO_SLEEP_SEC: 1
    ports:
      - 8080:8080
    depends_on:
      rabbit:
        condition: service_healthy